### ISSUE TITLE
trying this on linux

### ISSUE THREAD

**Issue by cmdocmd** [moien007/ENet.Managed#11]
Hello im trying to use this on linux and im getting this error while trying to connect

Segmentation fault (core dumped) while in windows it work any idea?

**Comment by moien007** [comment]
which version?

**Comment by cmdocmd** [comment]
4.2.0

**Comment by moien007** [comment]
I guess the problem resides in [here](https://github.com/moien007/ENet.Managed/blob/e48a0c5aeaf62192267c80a530f86a10fc826acb/src/ENet.Managed/Native/ENetHostOffsets.cs) because the offsets are Windows only back in 4.2.0 and below. That's why in version 5.x-alpha I'm using a custom version of ENet where I can retrieve these offsets via a helper function `enet_interophelper_sizeoroffset`.

**Comment by cmdocmd** [comment]
well in 5.0.0 im getting this error
Unhandled exception. ENet.Managed.ENetException: Failed to load ENet dynamic library. (Native last error: 0)
   at ENet.Managed.Internal.ThrowHelper.ThrowENetLibraryLoadFailed()
   at ENet.Managed.Native.LibENet.LoadDllFromFile(String path)
   at ENet.Managed.Native.LibENet.LoadModuleFromResource(Boolean overwrite)
   at ENet.Managed.Native.LibENet.Load()
   at ENet.Managed.ManagedENet.Startup(ENetStartupOptions startupOptions)
   at ENet.Managed.ManagedENet.Startup(ENetAllocator allocator)

**Comment by moien007** [comment]
Are you using a custom enet library?

**Comment by cmdocmd** [comment]
no i just downloaded it from nuget and i got this errors

**Comment by moien007** [comment]
> no i just downloaded it from nuget and i got this errors

`dlopen` is failing, I guess it's because when the library extracts the enet to the temp folder it doesn't have `Execute` permission.

**Comment by cmdocmd** [comment]
in 4.2.0 it was Executing with out issues

**Comment by cmdocmd** [comment]
![d1](https://user-images.githubusercontent.com/55096480/109317153-db3a6780-7865-11eb-87d2-4623c823273d.png)

**Comment by moien007** [comment]
Thanks for the screenshot. I'm busy on another project right now. It takes a while for me to get back on this project.

**Comment by cmdocmd** [comment]
any updates on this ?

**Comment by moien007** [comment]
> any updates on this ?

Sadly, no.

**Comment by moien007** [comment]
@cmdocmd Did `5.0.3.14-alpha` changes had any effect on the issue?

**Comment by cmdocmd** [comment]
![d1](https://user-images.githubusercontent.com/55096480/112043899-994dca00-8b62-11eb-829d-f0623a1c81a4.png)
i tried to use this version but still same issue

**Comment by moien007** [comment]
@cmdocmd 
The error is same as before?

**Comment by cmdocmd** [comment]
yeah its the same

**Comment by moien007** [comment]
`ThrowHelper.ThrowENetLibraryLoadFailed` is no longer being used.

> well in 5.0.0 im getting this error
> Unhandled exception. ENet.Managed.ENetException: Failed to load ENet dynamic library. (Native last error: 0)
> at **ENet.Managed.Internal.ThrowHelper.ThrowENetLibraryLoadFailed()**
> at ENet.Managed.Native.LibENet.LoadDllFromFile(String path)
> at ENet.Managed.Native.LibENet.LoadModuleFromResource(Boolean overwrite)
> at ENet.Managed.Native.LibENet.Load()
> at ENet.Managed.ManagedENet.Startup(ENetStartupOptions startupOptions)
> at ENet.Managed.ManagedENet.Startup(ENetAllocator allocator)

Are you sure you are getting the same error?

**Comment by cmdocmd** [comment]
![d1](https://user-images.githubusercontent.com/55096480/112721165-e7285080-8f1b-11eb-8b10-66a0ef27e20d.png)

yeah its not the same error

**Comment by moien007** [comment]
I have fixed this problem, I will push it soon.
