### ISSUE TITLE
ENetAsyncHost stops immediately after starting

### ISSUE THREAD

**Issue by JStalnac** [moien007/ENet.Managed#12]
ENetAsyncHost stops immediately after it's started. I believe the problem is in `ENetAsyncHost.RunServiceLoop`:

https://github.com/moien007/ENet.Managed/blob/c1cc588276038e2fa987d54f72fa0556ec5e9527/src/ENet.Managed/Async/ENetAsyncHost.cs#L490-L518

The condition in the outer `while` loop should be `!m_Stop` because `m_Stop != false` is only true when `m_Stop` is true, so when the host is shutting down, which means the service thread stops immediately.

I can prove my hypothesis by manually setting `m_Stop` to true with some hacky reflection at runtime before starting the host:

```cs
var field = typeof(ENetAsyncHost).GetField("m_Stop", BindingFlags.NonPublic | BindingFlags.Instance);
field.SetValue(myAsyncHost, true);
```

**Comment by moien007** [comment]
Great, Can you make a PR for that?

**Comment by JStalnac** [comment]
Sure!

**Comment by moien007** [comment]
Fixed in https://github.com/moien007/ENet.Managed/pull/13.
