### ISSUE TITLE
Missing - Last Ping Time / Round Trip Time

### ISSUE THREAD

**Issue by jczstudios** [moien007/ENet.Managed#15]
Is there any option for fetching the last ping time? I see the Ping method has been exposed but no way to actually access the value of a Peer's ping.

**Comment by moien007** [comment]
Oh, thanks for opening an issue regarding this.
I'll add them soon.

**Comment by moien007** [comment]
Done. https://github.com/moien007/ENet.Managed/commit/ffbd1c5c7cf6b4365e2019ff5de1ab795adfb33c
