### ISSUE TITLE
How to fix ENet host creation failed. ??

### ISSUE THREAD

**Issue by Fyrax-exe** [moien007/ENet.Managed#16]
Hello, im getting ENet host creation failed. how to fix it?

**Comment by smhman** [comment]
do you initialize enet with `ManagedENet.Startup();` before creating host? if you do, then please send error here

**Comment by Fyrax-exe** [comment]
yes ihave initialized it

**Comment by smhman** [comment]
could you send full error stackrace?

**Comment by smhman** [comment]
oops

**Comment by moien007** [comment]
What arguments you are passing to the constructor?

**Comment by Fyrax-exe** [comment]
Oh i got it fixed...

**Comment by smhman** [comment]
what was the solution?
