### ISSUE TITLE
Incorrect loading of ENet library

### ISSUE THREAD

**Issue by Nenkai** [moien007/ENet.Managed#3]
https://github.com/moien007/ENet.Managed/blob/9c840f10123f3df24d4ad1330a08f37d8fd50b81/ENet.Managed/LibENet.cs#L258

This line only checks against windows binaries resources which is will throw on linux, `Platform.Current.GetENetBinaryBytes()` has to be used instead.

**Comment by moien007** [comment]
Thanks for bug report. <3
