### ISSUE TITLE
[Question] Thread safety.

### ISSUE THREAD

**Issue by playingoDEERUX** [moien007/ENet.Managed#5]
Is this wrapper of ENet thread-safe as I make use of its StartServiceThread function which basically explains what I am talking about.

Do I need any further code to deal with thread safety or did the wrapper have it included/implemented?

**Comment by moien007** [comment]
It is thread-safe.

**Comment by moien007** [comment]
Since version `4.0.0-alpha` this library is no longer thread-safe.

**Comment by playingoDEERUX** [comment]
Oh, okay. Will thread-safety not be reworked again, why was it removed? It was very useful.

**Comment by moien007** [comment]
It wasn't the responsibility of this library to provide such a feature. But I'm working on an extension library called `ENet.Managed.Async` which allows you to work with ENet using `async\await` easily.
